module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.24.5

require github.com/operator-framework/operator-sdk v1.41.1 // cmd/operator-sdk -ldflags=-X=github.com/operator-framework/operator-sdk/internal/version.Version=v1.41.1 -tags 'containers_image_openpgp'
