name: release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  goreleaser:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Docker Login
        uses: docker/login-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set the release related variables
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo VERSION="$(echo "${GITHUB_REF#refs/tags/}" | sed 's/^v//')" >> $GITHUB_ENV
            echo GORELEASER_ARGS="--clean" >> $GITHUB_ENV
            echo ENABLE_RELEASE_PIPELINE=true >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            echo TAG=snapshot >> $GITHUB_ENV
            echo ENABLE_RELEASE_PIPELINE=true >> $GITHUB_ENV
          fi

      - name: Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ github.token }}
